# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [test-branch]
  pull_request:
    branches: [test-branch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      components-directory: ./components
      theme-directory: ./theme

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Installing components dependencies
        run: npm ci
        working-directory: ${{env.components-directory}}
      - name: Testing components
        run: npm test
        working-directory: ${{env.components-directory}}
      - name: Installing theme dependencies
        run: npm ci
        working-directory: ${{env.theme-directory}}
      - name: Testing theme
        run: npm test
        working-directory: ${{env.theme-directory}}
        
